language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
script:
    - pytest --cov=./
after_success:
    - codecovlanguage: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
script:
    - pytest
